spring:
  # conexion a bbdd
  datasource:
    url: jdbc:mariadb://localhost:3307:/airport-bath?createDatabaseIfNotExist=true
    username: root
    password: dbpw
    driver-class-name: org.mariadb.jdbc.Driver
  # tablas de spring bath gestionada de forma automatica
  batch:
    jdbc:
      initialize-schema: ALWAYS

server:
  port: 8082