spring:
  application:
    name: file-store-api

server:
  port: 8081

# Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean
  endpoint:
    health:
      enabled: false

application:
  store:
    # Dinamic resource path
    absolute-path: C:\Users\andre\eclipse-workspace\GitLab\TokioSpringLast\store
    relative-path: ..\store
    # User in memory
    login:
      users:
        - username: consumer
          # password = "password"
          password: "{bcrypt}$2a$10$GRLdNijSQMUvl/au9fL.eDwmoohzzS7.rmNSJ5.0Fx0/BTk76klW"
          authorities: read-rosurce
          roles: USER
        - username: producer
          # password = "password"
          password: "{bcrypt}$2a$10$GRLdNijSQMUvl/au9fL.eDwmoohzzS7.rmNSJ5.0Fx0/BTk76klW"
          authorities: read-rosurce, write-resource
          roles: USER, ADMIN
  # JWT Token
  jwt:
    secret: RxmgLW5HLjX9vpXHZwwgUlEEffs5fBC
    duration: PT1H