spring:
  application:
    name: file-store-api

server:
  port: 8081

# Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean
  endpoint:
    health:
      enabled: false

application:
  # Dinamic resource path
  store:
    absolute-path: C:\Users\andre\eclipse-workspace\GitLab\TokioSpringLast\store
    relative-path: ..\store
  # JWT Token
  jwt:
    secret: RxmgLW5HLjX9vpXHZwwgUlEEffs5fBC
    duration: PT1H