spring:
  application:
    name: flight-app
# Port
  port: 8080
# Docker compose
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: ./docker-compose.yml
# maria db docker
  datasource:
    url: jdbc:mariadb://localhost:3307/flight?createDatabaseIfNotExist=true
    username: root
    password: dbpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    #validate, none, update, create-drop
    hibernate:
      ddl-auto: create-drop
    # Debug queries
    show-sql: true
  test:
    database:
      replace: none
# i18n configuration, without message source bean
  messages:
    basename: message/message
    fallback-to-system-locale: true
# Liguibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development
    label-filter: development
  servlet:
    # Session
    session:
      timeout: 15m
      tracking-modes: COOKIE
    # Multipart
    multipart:
      max-file-size: 2MB
  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: andresruizpenuela@gmail.com
    password: 15356461
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
# DEBUG LOGS
#logging:
#  level:
#    org:
#      h2: DEBUG
#    "liquibase": DEBUG
    #Para ver los parámetros de las querys
    #org.hibernate.SQL: DEBUG
    #org.hibernate.orm.jdbc.bind: TRACE

# Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean, info, auditevents, env, sessions, shutdown, metrics, prometheus, logfile, loggers, configprops, conditions
  endpoint:
    health:
      enabled: false
# Dinamic resource path
application:
  store:
    absolute-path: C:\Users\andre\eclipse-workspace\GitLab\TokioSpringLast\store
    relative-path: ..\store