version: '3.8'
services:
  db:
    image: mariadb:latest
    container_name: mariadb_test
    restart: always
    environment:
      MARIADB_USER: db
      MARIADB_PASSWORD: db
      MARIADB_ROOT_PASSWORD: dbpw
      MARIADB_DATABASE: flight-test
    ports:
      - '3307:3306'
    volumes:
      - ../docker/working-mariadb_test:/var/lib/mysql
#  redis:
#    image: redis:latest
#    container_name: my-redis_test
#    ports:
#      - "6379:6379"
#    volumes:
#      - ../docker/redis-test:/data
#    command: ["redis-server", "--appendonly", "yes"]
  mongodb:
    image: mongo:latest
    container_name: mongdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpw
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes:
      - ../docker/mongo-data:/data/db
volumes:
  mongo-data:
    driver: local